(letrec ((make-grid (lambda (start dims) (let ((_45 (car dims))) (let ((_46 (list? _45))) (let ((_48 (if _46 (let ((_47 (car dims))) (set! dims _47)) #t))) (let ((_49 _48)) (let ((v (let ((_64 (car dims))) (make-vector _64 start)))) (let ((_50 (cdr dims))) (let ((_51 (null? _50))) (let ((_52 (not _51))) (let ((_62 (if _52 (letrec ((loop (lambda (i) (let ((_53 (car dims))) (let ((_54 (>= i _53))) (if _54 #t (let ((_55 (cdr dims))) (let ((_56 '())) (let ((_57 (cons _55 _56))) (let ((_58 (make-grid start _57))) (let ((_59 (vector-set! v i _58))) (let ((_60 _59)) (let ((_61 (+ i 1))) (loop _61)))))))))))))) (loop 0)) #t))) (let ((_63 _62)) v)))))))))))))
  (letrec ((grid-ref (lambda (g n) (let ((_32 (car n))) (let ((_33 (list? _32))) (let ((_35 (if _33 (let ((_34 (car n))) (set! n _34)) #t))) (let ((_36 _35)) (let ((_37 (cdr n))) (let ((_38 (null? _37))) (if _38 (let ((_39 (car n))) (vector-ref g _39)) (let ((_40 (car n))) (let ((_41 (vector-ref g _40))) (let ((_42 (cdr n))) (let ((_43 '())) (let ((_44 (cons _42 _43))) (grid-ref _41 _44))))))))))))))))
    (letrec ((grid-set! (lambda (g v n) (let ((_19 (car n))) (let ((_20 (list? _19))) (let ((_22 (if _20 (let ((_21 (car n))) (set! n _21)) #t))) (let ((_23 _22)) (let ((_24 (cdr n))) (let ((_25 (null? _24))) (if _25 (let ((_26 (car n))) (vector-set! g _26 v)) (let ((_27 (car n))) (let ((_28 (vector-ref g _27))) (let ((_29 (cdr n))) (let ((_30 '())) (let ((_31 (cons _29 _30))) (grid-set! _28 v _31))))))))))))))))
      (letrec ((t (let ((_18 '((4 5 6)))) (make-grid 0 _18))))
        (let ((_0 (display t)))
          (let ((_1 _0))
            (let ((_2 '24))
              (let ((_3 '((2 2 3))))
                (let ((_4 (grid-set! t _2 _3)))
                  (let ((_5 _4))
                    (let ((_6 '((2 2 3))))
                      (let ((_7 (grid-ref t _6)))
                        (let ((_8 (display _7)))
                          (let ((_9 _8))
                            (letrec ((u (let ((_17 '(2 2))) (make-grid #f _17))))
                              (let ((_10 (display t)))
                                (let ((_11 _10))
                                  (let ((_12 '(1 0)))
                                    (let ((_13 (grid-set! t #t _12)))
                                      (let ((_14 _13))
                                        (let ((_15 '(1 0)))
                                          (let ((_16 (grid-ref t _15)))
                                            (display _16)))))))))))))))))))))))
